# Generated by Django 5.1.7 on 2025-12-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_management', '0002_alter_event_end_time_alter_event_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
